resource "local_file" "pet" {
  filename        = var.filename
  content         = var.content
  file_permission = var.file_permission

  depends_on = [
    random_pet.my-pet
  ]

  lifecycle {
    create_before_destroy = true
  }
}

resource "local_file" "pet2" {
  filename        = var.filename
  content         = "My favorite pet is  ${random_pet.my-pet.id}"
  file_permission = var.file_permission
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.length
}

output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}


